import { StoreProvider } from "@/contexts/StoreProvider";
import Footer from "@/shared/Footer/Footer";
import Header from "@/shared/Header/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Suspense } from "react";
import { Bounce, ToastContainer } from "react-toastify";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Suspense fallback={<div>Loading...</div>}>
          <StoreProvider>
            <ToastContainer transition={Bounce} />
            <Header />
            {/* <LeftSidebar /> */}
            {children}
            <Footer />
          </StoreProvider>
        </Suspense>
      </body>
    </html>
  );
}
